import type { Metadata } from "next";
import ServicePage, { type ServiceData } from "../../components/ServicePage";

export const metadata: Metadata = {
  title: "AI Video Creation — diEntertainment",
  description:
    "AI-powered video production — commercials, product ads, cinematic reels, cartoon ads, and AI influencers built to convert.",
};

const data: ServiceData = {
  number: "05",
  slug: "ai-video-creation",
  category: "AI Video Creation",
  titleLines: ["AI VIDEO", "CREATION."],
  tagline:
    "Studio-quality video at a fraction of the cost and timeline — AI-generated content that looks real, performs better, and scales without limits.",
  pullquote: "Generated by AI. Built to convert.",
  description: [
    "The future of video production isn't a camera crew and a three-week timeline — it's AI that can produce broadcast-quality content in days.",
    "We harness the latest generative video models to create commercials, product ads, cinematic reels, and character-driven content that are indistinguishable from traditional production — and strategically engineered to perform.",
    "Whether you need a hyper-realistic brand spokesperson, an animated cartoon ad, or a full commercial with professional voiceover, our AI video pipeline delivers at a quality and speed that traditional production simply can't match.",
  ],
  deliverables: [
    {
      number: "01",
      title: "AI Commercials",
      description:
        "Full-length brand commercials generated with AI — scripted, directed, and produced to broadcast standard without the cost of a traditional shoot.",
    },
    {
      number: "02",
      title: "AI Product Ads",
      description:
        "High-converting product advertisement videos with photorealistic AI visuals, dynamic product showcases, and performance-optimised editing for paid media.",
    },
    {
      number: "03",
      title: "Cinematic Reels",
      description:
        "Stunning AI-generated cinematic reels built for brand storytelling, portfolio showcases, and social content that demands attention.",
    },
    {
      number: "04",
      title: "Cartoon Ads",
      description:
        "Custom animated cartoon-style ads with unique brand characters — engaging, memorable, and designed to cut through the noise on every platform.",
    },
    {
      number: "05",
      title: "Realistic AI Ads",
      description:
        "Photorealistic AI-generated video ads featuring lifelike environments, people, and product placements that look indistinguishable from live-action footage.",
    },
    {
      number: "06",
      title: "AI Influencers",
      description:
        "Fully custom AI brand ambassadors and digital influencers — consistent, on-brand, and available 24/7 without talent fees or scheduling conflicts.",
    },
    {
      number: "07",
      title: "Voiceover Ads",
      description:
        "AI-powered voiceover production with professional-grade vocal synthesis — any accent, tone, or language delivered at broadcast quality.",
    },
  ],
  process: [
    {
      number: "01",
      title: "Brief & Script",
      description:
        "We define your goals, audience, and message, then develop a creative script and visual direction tailored to your brand.",
    },
    {
      number: "02",
      title: "AI Generation",
      description:
        "Using the latest generative video models, we produce raw footage, characters, environments, and motion sequences to spec.",
    },
    {
      number: "03",
      title: "Edit & Sound",
      description:
        "Professional editing, colour grading, AI voiceover, licensed music, and sound design applied to every frame.",
    },
    {
      number: "04",
      title: "Delivery",
      description:
        "Final video delivered in all required formats and aspect ratios — ready for broadcast, paid media, and social platforms.",
    },
  ],
  ctaHeadline: "Let's create\nyour next ad.",
  packagesVariant: "ai",
};

export default function AIVideoCreationPage() {
  return <ServicePage {...data} />;
}
